name: monthly

on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  open-stats-update:
    name: Open new stats update issue
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: lowply/issue-from-template@v0.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IFT_TEMPLATE_NAME: monthly_stats.md

  close-stats-update:
    name: Close old stats update issues
    needs: open-stats-update
    runs-on: ubuntu-latest

    steps:
      - uses: lowply/auto-closer@v0.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AC_LABEL: "monthly-stats"
